services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: backend
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
    environment:
      MQTT_HOST_PROD: mosquitto
      MQTT_HOST_TEST: mosquitto
    networks:
      - app-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    ports:
      - "1883:1885"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: nginx
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
